### ISSUE TITLE
Error when using the lazy attribute

### ISSUE THREAD

**Issue by shantanubhadoria** [jonathanstowe/Attribute-Lazy#1]
Hi There :)
Thanks for this module. I am planning to put it to use but I get this error:

Here is my code

```
# lib/TestLazy.pm6
use Attribute::Lazy;

class TestLazy {
  has $.plugins will lazy {
    "aa";
  };
}
```

And when I use this class elsewhere:

```
# examples/test.p6
use v6;
use lib 'lib';

use Test;
say Test.new.plugins;
```

I get this error: 

```
===SORRY!===
Missing serialize REPR function for REPR SCRef
```

Hope thats a useful report, Cheers!

**Comment by shantanubhadoria** [comment]
Sorry I just realized that this is already filed in perl #127959
I guess you will want to keep track of that so I will leave this ticket open.

**Comment by jonathanstowe** [comment]
Yes it's a whole class of bugs around the serialisation of closures (a lot of places where wrap is used in compile time code such as a trait are afflicted,) it breaks several modules unfortunately.

But thanks anyway.

**Comment by jonathanstowe** [comment]
Hi,
It looks like the code above runs fun now. And looking at the RT ticket above it appears to be fixed,.

I'll close this for the time being.
